import { test, expect } from '@playwright/test';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
const path='/buildflow-digital-transformation/';
function monitor(page){const issues=[];page.on('pageerror',e=>issues.push(e.message));page.on('console',m=>{if(m.type()==='error')issues.push(m.text());});page.on('response',r=>{if(r.status()>=400)issues.push(`${r.status()} ${r.url()}`);});page.on('request',r=>{if(r.url().includes('/api/'))issues.push('Unexpected API request '+r.url());});return issues;}
test('public subpath: custody, damage evidence, dual approval, AI review and ERP simulation',async({page})=>{
 const issues=monitor(page);await page.goto(path);await expect(page).toHaveTitle('BuildFlow · Operations');await expect(page.getByRole('heading',{name:'Operations overview'})).toBeVisible();await expect(page.getByText('Interactive portfolio demo',{exact:true})).toBeVisible();
 await page.screenshot({path:join(tmpdir(),'buildflow-pages-desktop.png'),fullPage:true});
 await page.getByRole('link',{name:'Inventory',exact:true}).click();await page.getByRole('link',{name:/Hilti rotary hammer/}).click();await page.getByRole('button',{name:'Confirm checkout'}).click();await expect(page.locator('.actions .status').first()).toHaveText('Assigned');
 await page.getByLabel('Inspection findings').fill('Synthetic housing damage found on return');await page.getByRole('combobox',{name:'Condition',exact:true}).selectOption('damaged');await page.getByRole('button',{name:'Confirm return'}).click();await expect(page.locator('.actions .status').first()).toHaveText('Damaged');
 await page.getByRole('link',{name:'CLM-0003',exact:true}).click();await page.getByRole('button',{name:'Move to Submitted'}).click();await expect(page.getByRole('status')).toContainText('Evidence is required');await expect(page.locator('.actions .status').first()).toHaveText('Draft');
 await page.getByRole('button',{name:'Add evidence',exact:true}).click();await expect(page.getByAltText('synthetic-evidence.svg')).toBeVisible();expect(await page.getByAltText('synthetic-evidence.svg').evaluate(img=>img.complete&&img.naturalWidth>0)).toBe(true);
 await page.getByRole('button',{name:'Move to Submitted'}).click();await expect(page.locator('.actions .status').first()).toHaveText('Submitted');
 await page.selectOption('#role','Manager');await page.goto(path+'#claim/CLM-0001');await page.getByRole('button',{name:'Generate optional draft'}).click();await expect(page.getByText('AI-generated suggestion — human review required',{exact:false})).toBeVisible();await page.getByRole('button',{name:'Accept factual draft'}).click();await expect(page.getByText('Accepted',{exact:true})).toBeVisible();await expect(page.locator('.actions .status').first()).toHaveText('Under Review');
 await page.getByRole('button',{name:'Approve current revision'}).click();await expect(page.getByText(/Manager · MGR-001/)).toBeVisible();await expect(page.locator('.actions .status').first()).toHaveText('Under Review');await page.selectOption('#role','Finance');await page.getByRole('button',{name:'Approve current revision'}).click();await expect(page.locator('.actions .status').first()).toHaveText('Approved');
 await page.selectOption('#role','Administrator');await page.getByRole('link',{name:'Integrations',exact:true}).click();const row=page.getByRole('row').filter({hasText:'BF-CLM-0001-r1'});await row.getByRole('button',{name:'Simulate failure'}).click();await expect(row.getByText('Failed',{exact:true})).toBeVisible();await row.getByRole('button',{name:'Dispatch / retry'}).click();await expect(row.getByText('Delivered',{exact:true})).toBeVisible();
 expect(issues).toEqual([]);
});
test('changes survive reload; another visitor has its own seed; reset restores original data',async({page,browser})=>{
 const issues=monitor(page);await page.goto(path+'#asset/AST-001');await page.selectOption('#role','Employee');await page.getByRole('button',{name:'Confirm checkout'}).click();await expect(page.getByRole('status')).toContainText('not authorised');await expect(page.locator('.actions .status').first()).toHaveText('Available');
 await page.selectOption('#role','Warehouse');await page.getByRole('button',{name:'Confirm checkout'}).click();await expect(page.locator('.actions .status').first()).toHaveText('Assigned');await page.reload();await expect(page.locator('.actions .status').first()).toHaveText('Assigned');
 const visitor=await browser.newContext();try{const other=await visitor.newPage();await other.goto('http://127.0.0.1:4313'+path+'#asset/AST-001');await expect(other.locator('.actions .status').first()).toHaveText('Available');}finally{await visitor.close();}
 await page.getByRole('button',{name:'Reset demo'}).click();await expect(page.getByRole('status')).toContainText('Demo reset');await page.getByRole('link',{name:'Inventory',exact:true}).click();await page.getByRole('link',{name:/Hilti rotary hammer/}).click();await expect(page.locator('.actions .status').first()).toHaveText('Available');await expect(page.getByText('No movements yet.',{exact:false})).toBeVisible();expect(issues).toEqual([]);
});
test('mobile and synthetic file upload remain browser-local',async({page})=>{
 const issues=monitor(page);await page.setViewportSize({width:390,height:844});await page.goto(path);await expect(page.getByRole('button',{name:'Reset demo'})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.screenshot({path:join(tmpdir(),'buildflow-pages-mobile.png'),fullPage:true});
 await page.selectOption('#role','Employee');await page.getByRole('link',{name:'Create claim',exact:true}).click();await page.getByLabel('Description',{exact:true}).fill('Synthetic electrical cable damage, no real personal data');
 await page.locator('input[type=file]').setInputFiles({name:'synthetic.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+j9mQAAAAASUVORK5CYII=','base64')});
 await page.getByRole('button',{name:'Create draft',exact:true}).click();await expect(page.locator('.actions .status').first()).toHaveText('Draft');await expect(page.getByAltText('synthetic.png')).toBeVisible();expect(await page.getByAltText('synthetic.png').getAttribute('src')).toMatch(/^data:image\/png;base64,/);await page.reload();await expect(page.getByAltText('synthetic.png')).toBeVisible();expect(issues).toEqual([]);
});
