import {test,expect} from '@playwright/test';
const root='/buildflow-digital-transformation/',kit=root+'application-kit/';
test('Recruiter landing, source links and real downloads',async({page,request})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(kit);await expect(page.locator('#case-content')).toHaveAttribute('aria-busy','false');await expect(page.getByRole('heading',{name:'Construction Digital Transformation',exact:true})).toBeVisible();await expect(page.locator('.hero-actions a')).toHaveCount(4);await expect(page.locator('.evidence-list article')).toHaveCount(10);
 for(const [f,sig] of [['executive-summary.pdf','%PDF'],['case-study.pdf','%PDF'],['interview-deck.pdf','%PDF'],['interview-deck.pptx','PK']]){const r=await request.get(kit+'downloads/'+f);expect(r.status()).toBe(200);expect((await r.body()).subarray(0,4).toString()).toContain(sig);}
 await page.screenshot({path:'.scratch/landing-desktop.png',fullPage:true});expect(errors).toEqual([]);
});
test('Workspace navigation, evidence search and both case journeys',async({page})=>{
 await page.goto(kit+'workspace/');await expect(page.locator('#workspace-content')).toHaveAttribute('aria-busy','false');await expect(page.locator('#workspace-nav a')).toHaveCount(12);
 await page.getByRole('link',{name:'Processes',exact:true}).click();await expect(page.locator('.case-journey a')).toHaveCount(9);await page.getByRole('button',{name:'Damage claims case',exact:true}).click();await expect(page.locator('.case-journey a')).toHaveCount(9);
 await page.getByRole('link',{name:'Architecture',exact:true}).first().click();await expect(page.locator('.architecture-diagram')).toBeVisible();
 await page.getByRole('link',{name:'Overview',exact:true}).first().click();await expect(page.getByRole('heading',{name:'Transformation overview',exact:true})).toBeVisible();await page.screenshot({path:'.scratch/workspace-desktop.png',fullPage:true});await page.getByRole('searchbox').fill('invoice');await expect(page.locator('#workspace-content')).toContainText('Search');
});
test('Mobile landing and workspace stay within viewport',async({page})=>{
 await page.setViewportSize({width:390,height:844});for(const u of [kit,kit+'workspace/']){await page.goto(u);await expect(page.locator('[aria-busy]')).toHaveAttribute('aria-busy','false');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:u.endsWith('workspace/')?'.scratch/workspace-mobile.png':'.scratch/landing-mobile.png',fullPage:true});}
});
test('Single linked damaged return → reviewed suggestion → approval → mock ERP',async({page})=>{
 await page.goto(root);await page.getByRole('button',{name:'Start fresh 2-minute demo'}).click();await expect(page.locator('#return')).toBeVisible();await page.locator('#return textarea').fill('Housing cracked during operation; stop use pending inspection');await page.locator('#return select').selectOption('damaged');await page.getByRole('button',{name:'Confirm return',exact:true}).click();await expect(page.locator('#demo-guide')).toContainText('CLM-0003');await page.locator('#demo-guide a[href="#claim/CLM-0003"]').click();await page.locator('#evidence-form select').selectOption('synthetic://housing');await page.getByRole('button',{name:'Add evidence',exact:true}).click();await page.getByRole('button',{name:'Generate optional draft'}).click();await expect(page.locator('#app')).toContainText('AI recommendation ≠ business decision');await page.getByRole('button',{name:'Accept factual draft'}).click();await expect(page.locator('#app')).toContainText('Accepted');await page.getByRole('button',{name:'Move to Submitted'}).click();await page.locator('#role').selectOption('Manager');await page.getByRole('button',{name:'Move to Under Review'}).click();await page.locator('#estimate-form input').fill('420');await page.getByRole('button',{name:'Revise and invalidate approvals'}).click();await expect(page.locator('#estimate-form input')).toHaveValue('420');await page.getByRole('button',{name:'Approve current revision'}).click();await expect(page.locator('#app .status').first()).toHaveText('Approved');await page.locator('#role').selectOption('Administrator');await page.locator('#demo-guide a[href="#integrations"]').click();const row=page.getByRole('row').filter({hasText:'CLM-0003'});await row.getByRole('button',{name:'Dispatch / retry'}).click();await expect(row).toContainText('Delivered');await page.locator('#demo-guide a[href="#overview"]').click();await expect(page.locator('#app')).toContainText('Approved');expect(await page.locator('#app').innerText()).toContain('Damaged');
});
