import { readdirSync, readFileSync, existsSync } from 'node:fs';
import { resolve, dirname, join } from 'node:path';
import assert from 'node:assert/strict';
import BpmnModdle from 'bpmn-moddle';
import SwaggerParser from '@apidevtools/swagger-parser';
const root=process.cwd();function files(dir){return readdirSync(dir,{withFileTypes:true}).flatMap(e=>['.git','node_modules','data','test-results'].includes(e.name)?[]:e.isDirectory()?files(join(dir,e.name)):[join(dir,e.name)]);}
const all=files(root);let links=0;
for(const file of all.filter(f=>f.endsWith('.md'))){const text=readFileSync(file,'utf8');for(const match of text.matchAll(/!?\[[^\]]*\]\(([^)]+)\)/g)){const target=match[1].split('#')[0];if(!target||/^(https?:|mailto:)/.test(target))continue;const path=target.startsWith('/')?resolve(root,'.'+target):resolve(dirname(file),target);assert.ok(existsSync(path),`Broken link ${file} -> ${target}`);links++;}}
const t=JSON.parse(readFileSync('02-requirements/traceability.json'));const fields={br:'02-requirements/business-requirements.md',fr:'02-requirements/functional-requirements.md',story:'02-requirements/user-stories.md',ac:'02-requirements/acceptance-criteria.md',uat:'09-testing/uat-scenarios.md',kpi:'13-kpis/target-kpis.md'};
assert.equal(t.length,14);for(const row of t){for(const [field,file]of Object.entries(fields))assert.ok(readFileSync(file,'utf8').includes(row[field]),`Missing ${field} ${row[field]}`);assert.ok(existsSync(row.process));assert.ok(row.component.length>5);}
const bpmn=all.filter(f=>f.endsWith('.bpmn'));
for(const file of bpmn){const {rootElement,warnings}=await new BpmnModdle().fromXML(readFileSync(file,'utf8'));assert.equal(warnings.length,0,`${file}: ${warnings.map(w=>w.message)}`);const process=rootElement.rootElements.find(e=>e.$type==='bpmn:Process');const collab=rootElement.rootElements.find(e=>e.$type==='bpmn:Collaboration');assert.ok(collab.participants.length);assert.ok(process.laneSets[0].lanes.length>=2);assert.equal(process.isExecutable,false);const nodes=process.flowElements.filter(n=>n.$type!=='bpmn:SequenceFlow');const flow=process.flowElements.filter(n=>n.$type==='bpmn:SequenceFlow');const ids=new Set(process.flowElements.map(n=>n.id));assert.equal(ids.size,process.flowElements.length);for(const f of flow){assert.ok(ids.has(f.sourceRef.id)&&ids.has(f.targetRef.id));assert.ok(f.sourceRef.outgoing.includes(f));assert.ok(f.targetRef.incoming.includes(f));}const covered=process.laneSets[0].lanes.flatMap(l=>l.flowNodeRef.map(n=>n.id));assert.equal(covered.length,nodes.length);const di=rootElement.diagrams[0].plane.planeElement;for(const n of nodes)assert.ok(di.some(d=>d.bpmnElement?.id===n.id),`Missing DI ${n.id}`);for(const n of nodes.filter(n=>n.$type==='bpmn:ExclusiveGateway'&&n.outgoing.length>1))assert.ok(n.default&&n.outgoing.some(f=>f.conditionExpression));}
const contract=await SwaggerParser.validate('05-integrations/api-contracts/openapi.json');assert.equal(contract.openapi,'3.0.3');
const bc=JSON.parse(readFileSync('13-kpis/business-case.json'));const cash=bc.lossCashEUR+bc.duplicateCashEUR;const capacity=(bc.searchTasks*bc.searchMinutesSaved+bc.claimsPerYear*bc.adminMinutesSaved)/60*bc.hourlyValueEUR;assert.equal(cash,16800);assert.equal(Math.round(capacity),29458);assert.equal(Math.round(cash+capacity),46258);assert.equal((bc.oneOffEUR/(cash-bc.ongoingEUR)).toFixed(2),'5.83');
const uat=readFileSync('09-testing/uat-scenarios.md','utf8');assert.equal([...uat.matchAll(/^## UAT-INV-/gm)].length,12);assert.equal([...uat.matchAll(/^## UAT-CLM-/gm)].length,12);
const raci=readFileSync('12-governance/raci.md','utf8');for(const line of raci.split('\n').filter(l=>/^\|/.test(l)&&!l.includes('Activity')&&!l.includes('---')))assert.equal(line.split('|').filter(c=>c.trim()==='A').length,1,`One A required: ${line}`);
console.log(`PASS: ${links} local links; ${t.length} traced requirements; ${bpmn.length} BPMN models (moddle/DI/structure, not engine execution or OMG XSD); OpenAPI; 24 UAT cases; RACI; business-case arithmetic.`);
