import { browserMode, readState, writeCommand, resetDemo } from './client.js';
let state;const app=document.querySelector('#app'),role=document.querySelector('#role'),message=document.querySelector('#message');
role.value=sessionStorage.getItem('buildflowDemoRole')||'Warehouse';role.addEventListener('change',()=>{sessionStorage.setItem('buildflowDemoRole',role.value);render();});
const esc=v=>String(v??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const euro=n=>new Intl.NumberFormat('en-BE',{style:'currency',currency:'EUR'}).format((n||0)/100);
const date=v=>v?new Date(v).toLocaleString('en-BE'):'—';
const badge=s=>`<span class="status ${/Damaged|Review|Required|Failed|Lost|Pending|Dead Letter/.test(s)?'warn':/Assigned|Transit|Repair|Reserved/.test(s)?'info':''}">${esc(s)}</span>`;
const panel=(title,body,link='')=>`<section class="panel"><div class="panel-head"><h2>${title}</h2>${link}</div>${body}</section>`;
const table=(heads,rows)=>`<div class="table-scroll"><table><thead><tr>${heads.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')||`<tr><td colspan="${heads.length}">No records</td></tr>`}</tbody></table></div>`;
const siteName=id=>state.sites.find(s=>s.id===id)?.name||id;
const siteOptions=state=>state.sites.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('');
function feedback(text,error=false){message.textContent=text;message.className=error?'error':'';}
async function load(){state=await readState();render();app.setAttribute('aria-busy','false');}
let saving=false;
async function mutate(path,body,method='POST'){
 if(saving)return null;
 saving=true;
 try{const result=await writeCommand(path,body,role.value,method);await load();feedback(browserMode?'Saved in your browser demo. No business system was updated.':'Saved. History and operational state updated.');return result;}
 catch(e){feedback(e.message,true);return null;}
 finally{saving=false;}
}
const assetRows=assets=>assets.map(a=>`<tr><td><a href="#asset/${a.id}">${esc(a.name)}<small class="muted"> · ${a.id}</small></a></td><td>${esc(siteName(a.locationId))}</td><td>${badge(a.status)}</td><td>${esc(a.custodianId||'Warehouse')}</td></tr>`);
const claimRows=claims=>claims.map(c=>`<tr><td><a href="#claim/${c.id}">${c.id}</a></td><td>${esc(c.description.slice(0,52))}</td><td>${badge(c.status)}</td><td>${euro(c.estimatedCents)}</td></tr>`);
const history=(id)=>{const h=state.history.filter(x=>!id||x.entityId===id).slice(-12).reverse();return `<div class="timeline">${h.map(e=>`<p>${esc(e.action)} <small>${esc(e.entityId)} · ${esc(e.actor)} · ${date(e.at)}<br>${esc(e.reason||'')} · correlation ${esc(e.correlationId)}</small></p>`).join('')||'<p>No movements yet. Seed registry is not a fabricated custody history.</p>'}</div>`;};
function render(){if(!state)return;const route=location.hash.slice(1)||'overview';document.querySelectorAll('nav a').forEach(a=>a.classList.toggle('active',route.startsWith(a.hash.slice(1))));
const titles={overview:'Operations overview',inventory:'Inventory',claims:'Damage claims',integrations:'Integrations',create:'Create damage claim',asset:'Asset detail',claim:'Damage claim detail'};document.querySelector('#page-title').textContent=titles[route.split('/')[0]]||'Operations overview';
if(route==='overview'){
 const active=state.claims.filter(c=>!['Closed','Rejected','Draft'].includes(c.status)),pending=state.outbox.filter(e=>e.status!=='Delivered');
 app.innerHTML=`<div class="metrics">${[['Assets tracked',state.assets.length],['Open claims',active.length],['Awaiting approval',state.claims.filter(c=>c.status==='Under Review').length],['ERP queue',pending.length]].map(([s,n])=>`<div class="metric"><span>${s}</span><strong>${n}</strong></div>`).join('')}</div>`+panel('Inventory',table(['Asset','Location','Status','Responsible'],assetRows(state.assets.slice(0,5))),'<a href="#inventory">View all assets</a>')+`<div class="lower">${panel('Claims requiring attention',table(['Claim ID','Issue','Status','Estimated cost'],claimRows(active)),'<a href="#claims">View all claims</a>')}${panel('Recent activity',`<div class="panel-body">${history()}</div>`)}</div><p class="muted">SLA demo deadlines use an approximate 14 elapsed days. Production uses the business-calendar rules documented in TO-BE. ${active.filter(c=>new Date(c.dueAt)<new Date()).length} demo claims past resolution deadline.</p>`;
}else if(route==='inventory'){
 app.innerHTML=`<div class="toolbar"><label>Search assets<input id="search" placeholder="Name, asset ID or serial"></label><label>Status<select id="filter"><option value="">All statuses</option>${[...new Set(state.assets.map(a=>a.status))].map(s=>`<option>${s}</option>`).join('')}</select></label></div>`+panel('Tracked assets',table(['Asset','Location','Status','Responsible'],assetRows(state.assets)));
 const filter=()=>{const q=document.querySelector('#search').value.toLowerCase(),st=document.querySelector('#filter').value;document.querySelector('tbody').innerHTML=assetRows(state.assets.filter(a=>(`${a.name} ${a.id} ${a.serial}`.toLowerCase().includes(q))&&(!st||st===a.status))).join('')||'<tr><td colspan="4">No matching assets</td></tr>';};document.querySelector('#search').oninput=filter;document.querySelector('#filter').onchange=filter;
}else if(route.startsWith('asset/'))assetDetail(route.split('/')[1]);
else if(route==='claims')app.innerHTML=panel('Claims register',table(['Claim ID','Description','Status','Estimated cost'],claimRows(state.claims)))+'<p class="muted">Drafts are included in this register; dashboard operational counts exclude Draft, Closed and Rejected.</p>';
else if(route.startsWith('claim/'))claimDetail(route.split('/')[1]);
else if(route==='create')claimForm();
else if(route==='integrations')integrations();
else{location.hash='overview';}
}
function assetDetail(id){const a=state.assets.find(a=>a.id===id);if(!a){app.innerHTML='<p>Asset not found.</p>';return;}
 const facts=[['Asset ID',a.id],['Category',a.category],['Brand / model',`${a.brand} / ${a.model}`],['Serial',a.serial||a.serialException],['Location',siteName(a.locationId)],['Custodian',a.custodianId],['Purchase date · ERP',a.purchaseDate],['Acquisition · ERP',euro(a.purchaseCents)],['Book value · ERP',euro(a.currentValueCents)],['Operational state',a.status],['ERP reference',a.erpAssetId],['QR payload',`asset:${a.id}`]];
 let form='';if(['Available','Reserved'].includes(a.status))form=`<h3>Check out</h3><form id="checkout" class="form-grid"><label>Construction site<select name="siteId">${siteOptions(state)}</select></label><label>Responsible employee<select name="custodianId">${state.employees.map(e=>`<option>${e}</option>`).join('')}</select></label><button>Confirm checkout</button></form>`;
 if(a.status==='Assigned')form=`<h3>Return inspection</h3><form id="return" class="form-grid"><label class="wide">Inspection findings<textarea name="inspection" required minlength="3" placeholder="Describe condition before returning"></textarea></label><label>Condition<select name="condition"><option value="clean">Clean / safe</option><option value="damaged">Damaged — quarantine + Draft claim</option></select></label><button>Confirm return</button></form><hr><h3>Transfer between sites</h3><form id="transfer" class="form-grid"><label>Destination<select name="siteId">${siteOptions(state)}</select></label><button>Dispatch transfer</button></form>`;
 if(a.status==='In Transit')form=`<h3>Confirm destination receipt</h3><p>Sender retains custody until receipt. Pending destination: ${esc(siteName(a.transferTo))}.</p><form id="receive" class="form-grid"><label>Receiving site<select name="siteId">${siteOptions(state)}</select></label><label>Receiving custodian<select name="custodianId">${state.employees.map(e=>`<option>${e}</option>`).join('')}</select></label><button>Confirm receipt</button></form>`;
 app.innerHTML=`<a href="#inventory">← Inventory</a><div class="actions">${badge(a.status)}<strong>${esc(a.name)}</strong></div>`+panel('Asset record',`<div class="panel-body"><dl class="facts">${facts.map(([l,v])=>`<div><dt>${l}</dt><dd>${esc(v)}</dd></div>`).join('')}</dl>${a.lastClaimId?`<p>Damage draft: <a href="#claim/${a.lastClaimId}">${a.lastClaimId}</a></p>`:''}</div>`)+panel('Custody actions',`<div class="panel-body">${role.value!=='Warehouse'?'<div class="notice">Choose demo Warehouse to operate custody commands.</div>':''}${form||'<p>No circulation action while unsafe, lost or out of service. Maintenance/loss/retirement are target design processes outside this UI.</p>'}</div>`)+panel('History',`<div class="panel-body">${history(a.id)}</div>`);
 for(const op of ['checkout','return','transfer','receive']){const f=document.querySelector('#'+op);if(f)f.onsubmit=async e=>{e.preventDefault();const b=Object.fromEntries(new FormData(f));if(op==='return'){b.damaged=b.condition==='damaged';delete b.condition;}b.expectedVersion=a.version;await mutate(`/api/assets/${a.id}/${op}`,b);};}
}
async function getEvidence(f){const input=f.querySelector('[name=file]');const file=input.files[0];if(!file)return [];
 if(file.size>2000000 || !['image/png','image/jpeg','application/pdf'].includes(file.type))throw new Error('Select PNG/JPEG/PDF ≤2MB; no real personal data.');
 const data=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file);});return[{name:file.name,kind:file.type.startsWith('image/')?'image':'document',data}];}
function claimForm(){app.innerHTML=`<div class="notice">${browserMode?'Browser simulation only. Evidence and changes stay in this browser; use synthetic examples.':'Synthetic demonstration only. Save draft is unconfirmed until the server accepts it. Evidence is stored locally without production scanning.'}</div>`+panel('Incident facts',`<div class="panel-body"><form id="create-form" class="form-grid"><label>Asset<select name="assetId">${state.assets.map(a=>`<option value="${a.id}">${a.id} · ${esc(a.name)}</option>`).join('')}</select></label><label>Site<select name="siteId">${siteOptions(state)}</select></label><label class="wide">Description<textarea name="description" required minlength="3" placeholder="Describe observable facts, not blame"></textarea></label><label>Severity<select name="severity"><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>CRITICAL</option></select></label><label>Category<select name="category"><option>Mechanical</option><option>Electrical</option><option>Structural</option><option>Other</option></select></label><label>Estimated repair cost · EUR<input name="cost" type="number" min="0" max="1000000" step="0.01" value="0" required></label><label>Third party · optional<input name="thirdParty" maxlength="150"></label><label class="wide">Evidence · synthetic PNG/JPEG/PDF ≤2MB<input type="file" name="file" accept="image/png,image/jpeg,application/pdf"></label><label>Use existing synthetic evidence<select name="synthetic"><option value="">None yet</option><option value="synthetic://hose">Illustrative hose image</option><option value="synthetic://housing">Illustrative housing image</option></select></label><div class="actions wide"><button type="submit">Create draft</button><button type="button" class="secondary" id="save-local">Save unconfirmed local draft</button><button type="button" class="secondary" id="restore-local">Restore local draft</button></div></form><p class="draft-note">${browserMode?'Drafts and accepted actions here are simulations, not real custody confirmations.':'Online validation is required for confirmed claim/custody.'} Local draft excludes evidence binaries; attach evidence after restore.</p></div>`);
 const f=document.querySelector('#create-form');document.querySelector('#save-local').onclick=()=>{const b=Object.fromEntries(new FormData(f));delete b.file;localStorage.setItem('buildflowDraft',JSON.stringify(b));feedback('Local draft saved — UNCONFIRMED. No server transaction occurred.');};document.querySelector('#restore-local').onclick=()=>{const b=JSON.parse(localStorage.getItem('buildflowDraft')||'null');if(!b){feedback('No local draft stored.');return;}for(const[k,v]of Object.entries(b))if(f.elements[k])f.elements[k].value=v;feedback(browserMode?'Unconfirmed draft restored; review before creating a demo claim.':'Unconfirmed draft restored; review and validate online.');};
 f.onsubmit=async e=>{e.preventDefault();try{const b=Object.fromEntries(new FormData(f));const ev=await getEvidence(f);if(b.synthetic)ev.push({name:'synthetic-evidence.svg',kind:'image',reference:b.synthetic});const payload={assetId:b.assetId,siteId:b.siteId,description:b.description,severity:b.severity,category:b.category,thirdParty:b.thirdParty||null,estimatedCents:Math.round(Number(b.cost)*100),evidence:ev};const c=await mutate('/api/damage-claims',payload);if(c){location.hash=`claim/${c.id}`;localStorage.removeItem('buildflowDraft');}}catch(e){feedback(e.message,true);}};
}
function claimDetail(id){const c=state.claims.find(c=>c.id===id);if(!c){app.innerHTML='<p>Claim not found.</p>';return;}const a=state.assets.find(a=>a.id===c.assetId);
 const facts=[['Asset',`${c.assetId} · ${a?.name}`],['Site',siteName(c.siteId)],['Reporter',c.reporterId],['Liability · human only',c.liability],['Estimate',euro(c.estimatedCents)],['Actual · reconciled ERP',c.actualCents===null?'Awaiting invoice':euro(c.actualCents)],['Severity / category',`${c.severity} / ${c.category}`],['Revision / version',`${c.revision} / ${c.version}`],['Resolution deadline · demo',date(c.dueAt)],['Third party',c.thirdParty||'None recorded']];
 const next={Draft:'Submitted',Submitted:'Under Review','Information Required':'Under Review',Approved:'Repair Scheduled','Repair Scheduled':'In Repair','In Repair':'Awaiting Invoice','Awaiting Invoice':'Closed',Closed:'Under Review'}[c.status];
 const evidence=c.evidence.map(e=>{const src=e.reference==='synthetic://hose'?'./evidence-hose.svg':e.reference==='synthetic://housing'?'./evidence-housing.svg':e.data;return `<div>${e.kind==='image'&&src?`<img src="${esc(src)}" alt="${esc(e.name)}">`:'<p>Document stored in local demo</p>'}<small>${esc(e.name)}</small></div>`;}).join('')||'<p>No evidence yet — submission blocked.</p>';
 const sug=c.aiSuggestions.at(-1);const ai=sug?`<div class="notice">AI-generated suggestion — human review required<br>AI recommendation ≠ business decision</div><p>${esc(sug.summary)}</p><p>Suggested category: <strong>${esc(sug.suggestedCategory||'Clarification needed')}</strong></p><p class="muted">Missing: ${esc(sug.missingInformation.join('; '))}. ${esc(sug.scoreMeaning)} (${sug.score}). Prompt ${sug.promptVersion} · ${sug.model}.</p><p>Human review: <strong>${esc(sug.reviewStatus)}</strong></p>${sug.reviewStatus==='Pending'?'<div class="actions"><button data-ai="Accepted">Accept factual draft</button><button class="secondary" data-ai="Dismissed">Dismiss suggestion</button></div>':''}`:'<p>Optional deterministic mock. No live AI service is called.</p>';
 app.innerHTML=`<a href="#claims">← Claims register</a><div class="actions"><strong>${c.id}</strong>${badge(c.status)}</div>`+panel('Claim facts',`<div class="panel-body"><p>${esc(c.description)}</p><dl class="facts">${facts.map(([l,v])=>`<div><dt>${l}</dt><dd>${esc(v)}</dd></div>`).join('')}</dl></div>`)+panel('Evidence',`<div class="panel-body"><div class="evidence-grid">${evidence}</div>${['Draft','Under Review','Information Required'].includes(c.status)?'<form id="evidence-form" class="actions"><label>Add synthetic image<select name="reference"><option value="synthetic://hose">Hose illustration</option><option value="synthetic://housing">Housing illustration</option></select></label><button class="secondary">Add evidence</button></form><p class="muted">Adding evidence invalidates any existing approvals.</p>':''}</div>`)+panel('Workflow and approvals',`<div class="panel-body"><p>${c.estimatedCents>500000?'Above €5,000: Manager plus Finance approval required. Operations notified in target flow.':'At/below €5,000: Manager approval required.'} Reporter cannot approve.</p><div class="actions">${next?`<button id="next-status">${c.status==='Closed'?'Reopen with reason':`Move to ${next}`}</button>`:''}${c.status==='Under Review'?'<button id="approve">Approve current revision</button><button class="secondary" id="request-info">Request information</button><button class="secondary" id="reject">Reject with reason</button>':''}</div><label>Decision reason / inspection outcome<input id="reason" placeholder="Required for decisions" value="Reviewed evidence and repair need"></label>${c.status==='Awaiting Invoice'?'<div class="form-grid"><label>Actual EUR<input id="actual" type="number" min="0" step="0.01"></label><label>ERP invoice reference<input id="invoice"></label><label>Demo Finance reconciliation<select id="reconciled"><option value="false">Not reconciled</option><option value="true">Confirmed in mock ERP</option></select></label></div>':''}<ul>${c.approvals.map(a=>`<li>${esc(a.role)} · ${esc(a.actor)} · revision ${a.revision} · ${euro(a.amountCents)} · ${esc(a.reason)}</li>`).join('')||'<li>No current approvals</li>'}</ul>${['Under Review','Information Required'].includes(c.status)?`<form id="estimate-form" class="actions"><label>Revise estimate · EUR<input name="cost" type="number" step="0.01" min="0" value="${c.estimatedCents/100}"></label><button class="secondary">Revise and invalidate approvals</button></form>`:''}</div>`)+panel('AI draft assistant',`<div class="panel-body">${ai}<button class="secondary" id="generate-ai">Generate optional draft</button></div>`)+panel('Comments and timeline',`<div class="panel-body">${c.comments.map(x=>`<p>${esc(x.text)} <small class="muted">${esc(x.actor)}</small></p>`).join('')}<form id="comment-form" class="actions"><label>Comment<input name="text" required minlength="3" maxlength="1000"></label><button class="secondary">Add comment</button></form>${history(c.id)}</div>`);
 const base=`/api/damage-claims/${c.id}`;const reason=()=>document.querySelector('#reason').value;
 if(document.querySelector('#next-status'))document.querySelector('#next-status').onclick=()=>mutate(base+'/status',{status:next,expectedVersion:c.version,reason:reason(),...(next==='Closed'?{actualCents:Math.round(Number(document.querySelector('#actual').value)*100),invoiceRef:document.querySelector('#invoice').value,repairOutcome:reason(),reconciled:document.querySelector('#reconciled').value==='true'}:{})},'PATCH');
 if(document.querySelector('#approve'))document.querySelector('#approve').onclick=()=>mutate(base+'/approve',{expectedVersion:c.version,reason:reason()});
 for(const [id,status]of [['request-info','Information Required'],['reject','Rejected']])if(document.querySelector('#'+id))document.querySelector('#'+id).onclick=()=>mutate(base+'/status',{expectedVersion:c.version,status,reason:reason()},'PATCH');
 const evidenceForm=document.querySelector('#evidence-form');if(evidenceForm)evidenceForm.onsubmit=e=>{e.preventDefault();mutate(base+'/evidence',{expectedVersion:c.version,evidence:[{name:'synthetic-evidence.svg',kind:'image',reference:new FormData(evidenceForm).get('reference')}]});};
 const ef=document.querySelector('#estimate-form');if(ef)ef.onsubmit=e=>{e.preventDefault();mutate(base+'/estimate',{estimatedCents:Math.round(Number(new FormData(ef).get('cost'))*100),expectedVersion:c.version},'PATCH');};
 document.querySelector('#generate-ai').onclick=()=>mutate(base+'/ai',{expectedVersion:c.version});
 document.querySelectorAll('[data-ai]').forEach(b=>b.onclick=()=>mutate(base+'/ai-review',{expectedVersion:c.version,suggestionId:sug.id,decision:b.dataset.ai}));
 document.querySelector('#comment-form').onsubmit=e=>{e.preventDefault();mutate(base+'/comment',{expectedVersion:c.version,text:new FormData(e.target).get('text')});};
}
function integrations(){app.innerHTML='<div class="notice">Mocked ERP adapter. Administrator can simulate failure and replay. Stable external reference deduplicates delivery. No real accounting is performed.</div>'+panel('Outbox and delivery ledger',table(['Event / business reference','Status','Attempts','ERP receipt','Action'],state.outbox.map(e=>`<tr><td>${esc(e.entityId)}<br><small class="muted">${esc(e.externalRef)}</small></td><td>${badge(e.status)}</td><td>${e.attempts}</td><td>${esc(e.erpRef)}</td><td><button data-dispatch="${e.id}" data-fail="true" class="secondary">Simulate failure</button> <button data-dispatch="${e.id}">Dispatch / retry</button></td></tr>`)))+'<p class="muted">Production uses scheduled backoff, authenticated adapters, reference lookup on ambiguous response and Finance reconciliation. Manual demo buttons model the state, not those services.</p>';document.querySelectorAll('[data-dispatch]').forEach(b=>b.onclick=()=>mutate(`/api/integrations/${b.dataset.dispatch}/dispatch`,{simulateFailure:b.dataset.fail==='true'}));}
if(browserMode){
 const banner=document.createElement('section');banner.className='demo-banner';banner.setAttribute('aria-label','Public demo');
 banner.innerHTML='<div><strong>Interactive portfolio demo</strong><span>Fictional data · Your changes stay in this browser · ERP and AI are simulated</span></div><div class="actions"><a href="https://github.com/phlppgdfry/buildflow-digital-transformation" target="_blank" rel="noopener">View case study</a><button class="secondary" id="reset-demo">Reset demo</button></div>';
 document.querySelector('#message').before(banner);
 document.querySelector('footer span').textContent='BuildFlow Group · Browser simulation';
 document.querySelector('#reset-demo').onclick=async()=>{
  if(saving)return;
  saving=true;
  try{await resetDemo();localStorage.removeItem('buildflowDraft');sessionStorage.removeItem('buildflowDemoRole');role.value='Warehouse';location.hash='overview';await load();feedback('Demo reset to the original fictional data.');}
  catch(e){feedback(e.message,true);}
  finally{saving=false;}
 };
}
window.addEventListener('hashchange',()=>{feedback('');render();});load().catch(e=>{app.setAttribute('aria-busy','false');app.textContent='Demo data could not be loaded. Reload the page to try again.';feedback(e.message,true);});
